### Importing necessary modules

In [1]:
import pandas as pd
import numpy as np
import os
import numpy as np
import requests
import json
#Reading the data from csv and storing the df in empty dictionary
years = [2015,2016,2017,2018,2019]
df={}
for year in years:
    url = f"../Resources/{year}.csv"
    pd.set_option("display.max_rows",800)
    df[year] = pd.read_csv(url)

# 1.1 Importing Raw Data
### Cleaning the df over the period 2016-2019

In [2]:
#Unpacking the df
df_2015,df_2016,df_2017,df_2018,df_2019 = df[2015],df[2016],df[2017],df[2018],df[2019]

In [3]:
# Checking for null values in the df
for year in years:
    print(f"""{year} \n{df[year].isna().sum()}
----------""")

2015
Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64
----------
2016
Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Lower Confidence Interval        0
Upper Confidence Interval        0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64
----------
2017
Country                          0
Happiness.Rank                   0
Happiness.Score                  0
Whisker.high                     0
Whisker.low                      0
Economy..GDP.per.Capita.         0
Family                           0
Health..Life.Expectancy.         0
Freedom                          0
Generosity                       0
Trust..Government.Corruption.    0
Dystopia.Residual                0
dtype: int64
----------
2018
Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       1
dtype: int64
----------
2019
Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64
----------

In [4]:
# Checked for null values - replaced it with with zero.
df_2018.fillna(0,inplace = True)
df_2018.isna().sum()

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [5]:
# replacing spaces with underscore
for year in years:
    df[year].columns = [x.replace(" ","_") for x in df[year].columns.values]
    print(f"""{year} \n{df[year].columns}
----------""")

2015
Index(['Country', 'Region', 'Happiness_Rank', 'Happiness_Score',
       'Standard_Error', 'Economy_(GDP_per_Capita)', 'Family',
       'Health_(Life_Expectancy)', 'Freedom', 'Trust_(Government_Corruption)',
       'Generosity', 'Dystopia_Residual'],
      dtype='object')
----------
2016
Index(['Country', 'Region', 'Happiness_Rank', 'Happiness_Score',
       'Lower_Confidence_Interval', 'Upper_Confidence_Interval',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Trust_(Government_Corruption)', 'Generosity',
       'Dystopia_Residual'],
      dtype='object')
----------
2017
Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')
----------
2018
Index(['Overall_rank', 'Country_or_region', 'Score', 'GDP_per_capita',
       'Social_support', 'Healthy_life_expectancy',
       'Freedom_to_make_life_choices', 'Generosity',
       'Perceptions_of_corruption'],
      dtype='object')
----------
2019
Index(['Overall_rank', 'Country_or_region', 'Score', 'GDP_per_capita',
       'Social_support', 'Healthy_life_expectancy',
       'Freedom_to_make_life_choices', 'Generosity',
       'Perceptions_of_corruption'],
      dtype='object')
----------

In [6]:
#Removing non-contributing columns of the df 
col = ['Lower_Confidence_Interval','Upper_Confidence_Interval','Region','Whisker.high','Whisker.low','Standard_Error']
for year in years:
    for value in df[year].columns:
          if value in col:
            del df[year][value]

df[2019]

,Overall_rank,Country_or_region,Score,GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
5,6,Switzerland,7.480,1.452,1.526,1.052,0.572,0.263,0.343
6,7,Sweden,7.343,1.387,1.487,1.009,0.574,0.267,0.373
7,8,New Zealand,7.307,1.303,1.557,1.026,0.585,0.330,0.380
8,9,Canada,7.278,1.365,1.505,1.039,0.584,0.285,0.308
9,10,Austria,7.246,1.376,1.475,1.016,0.532,0.244,0.226
10,11,Australia,7.228,1.372,1.548,1.036,0.557,0.332,0.290
11,12,Costa Rica,7.167,1.034,1.441,0.963,0.558,0.144,0.093
12,13,Israel,7.139,1.276,1.455,1.029,0.371,0.261,0.082
13,14,Luxembourg,7.090,1.609,1.479,1.012,0.526,0.194,0.316
14,15,United Kingdom,7.054,1.333,1.538,0.996,0.450,0.348,0.278
15,16,Ireland,7.021,1.499,1.553,0.999,0.516,0.298,0.310
16,17,Germany,6.985,1.373,1.454,0.987,0.495,0.261,0.265
17,18,Belgium,6.923,1.356,1.504,0.986,0.473,0.160,0.210
18,19,United States,6.892,1.433,1.457,0.874,0.454,0.280,0.128
19,20,Czech Republic,6.852,1.269,1.487,0.920,0.457,0.046,0.036
20,21,United Arab Emirates,6.825,1.503,1.310,0.825,0.598,0.262,0.182
21,22,Malta,6.726,1.300,1.520,0.999,0.564,0.375,0.151
22,23,Mexico,6.595,1.070,1.323,0.861,0.433,0.074,0.073
23,24,France,6.592,1.324,1.472,1.045,0.436,0.111,0.183
24,25,Taiwan,6.446,1.368,1.430,0.914,0.351,0.242,0.097
25,26,Chile,6.444,1.159,1.369,0.920,0.357,0.187,0.056
26,27,Guatemala,6.436,0.800,1.269,0.746,0.535,0.175,0.078
27,28,Saudi Arabia,6.375,1.403,1.357,0.795,0.439,0.080,0.132
28,29,Qatar,6.374,1.684,1.313,0.871,0.555,0.220,0.167
29,30,Spain,6.354,1.286,1.484,1.062,0.362,0.153,0.079
30,31,Panama,6.321,1.149,1.442,0.910,0.516,0.109,0.054
31,32,Brazil,6.300,1.004,1.439,0.802,0.390,0.099,0.086
32,33,Uruguay,6.293,1.124,1.465,0.891,0.523,0.127,0.150
33,34,Singapore,6.262,1.572,1.463,1.141,0.556,0.271,0.453
34,35,El Salvador,6.253,0.794,1.242,0.789,0.430,0.093,0.074
35,36,Italy,6.223,1.294,1.488,1.039,0.231,0.158,0.030
36,37,Bahrain,6.199,1.362,1.368,0.871,0.536,0.255,0.110
37,38,Slovakia,6.198,1.246,1.504,0.881,0.334,0.121,0.014
38,39,Trinidad & Tobago,6.192,1.231,1.477,0.713,0.489,0.185,0.016
39,40,Poland,6.182,1.206,1.438,0.884,0.483,0.117,0.050
40,41,Uzbekistan,6.174,0.745,1.529,0.756,0.631,0.322,0.240
41,42,Lithuania,6.149,1.238,1.515,0.818,0.291,0.043,0.042
42,43,Colombia,6.125,0.985,1.410,0.841,0.470,0.099,0.034
43,44,Slovenia,6.118,1.258,1.523,0.953,0.564,0.144,0.057
44,45,Nicaragua,6.105,0.694,1.325,0.835,0.435,0.200,0.127
45,46,Kosovo,6.100,0.882,1.232,0.758,0.489,0.262,0.006
46,47,Argentina,6.086,1.092,1.432,0.881,0.471,0.066,0.050
47,48,Romania,6.070,1.162,1.232,0.825,0.462,0.083,0.005
48,49,Cyprus,6.046,1.263,1.223,1.042,0.406,0.190,0.041
49,50,Ecuador,6.028,0.912,1.312,0.868,0.498,0.126,0.087
50,51,Kuwait,6.021,1.500,1.319,0.808,0.493,0.142,0.097
51,52,Thailand,6.008,1.050,1.409,0.828,0.557,0.359,0.028
52,53,Latvia,5.940,1.187,1.465,0.812,0.264,0.075,0.064
53,54,South Korea,5.895,1.301,1.219,1.036,0.159,0.175,0.056
54,55,Estonia,5.893,1.237,1.528,0.874,0.495,0.103,0.161
55,56,Jamaica,5.890,0.831,1.478,0.831,0.490,0.107,0.028
56,57,Mauritius,5.888,1.120,1.402,0.798,0.498,0.215,0.060
57,58,Japan,5.886,1.327,1.419,1.088,0.445,0.069,0.140
58,59,Honduras,5.860,0.642,1.236,0.828,0.507,0.246,0.078
59,60,Kazakhstan,5.809,1.173,1.508,0.729,0.410,0.146,0.096
60,61,Bolivia,5.779,0.776,1.209,0.706,0.511,0.137,0.064
61,62,Hungary,5.758,1.201,1.410,0.828,0.199,0.081,0.020
62,63,Paraguay,5.743,0.855,1.475,0.777,0.514,0.184,0.080
63,64,Northern Cyprus,5.718,1.263,1.252,1.042,0.417,0.191,0.162
64,65,Peru,5.697,0.960,1.274,0.854,0.455,0.083,0.027
65,66,Portugal,5.693,1.221,1.431,0.999,0.508,0.047,0.025
66,67,Pakistan,5.653,0.677,0.886,0.535,0.313,0.220,0.098
67,68,Russia,5.648,1.183,1.452,0.726,0.334,0.082,0.031
68,69,Philippines,5.631,0.807,1.293,0.657,0.558,0.117,0.107
69,70,Serbia,5.603,1.004,1.383,0.854,0.282,0.137,0.039
70,71,Moldova,5.529,0.685,1.328,0.739,0.245,0.181,0.000
71,72,Libya,5.525,1.044,1.303,0.673,0.416,0.133,0.152
72,73,Montenegro,5.523,1.051,1.361,0.871,0.197,0.142,0.080
73,74,Tajikistan,5.467,0.493,1.098,0.718,0.389,0.230,0.144
74,75,Croatia,5.432,1.155,1.266,0.914,0.296,0.119,0.022
75,76,Hong Kong,5.430,1.438,1.277,1.122,0.440,0.258,0.287
76,77,Dominican Republic,5.425,1.015,1.401,0.779,0.497,0.113,0.101
77,78,Bosnia and Herzegovina,5.386,0.945,1.212,0.845,0.212,0.263,0.006
78,79,Turkey,5.373,1.183,1.360,0.808,0.195,0.083,0.106
79,80,Malaysia,5.339,1.221,1.171,0.828,0.508,0.260,0.024
80,81,Belarus,5.323,1.067,1.465,0.789,0.235,0.094,0.142
81,82,Greece,5.287,1.181,1.156,0.999,0.067,0.000,0.034
82,83,Mongolia,5.285,0.948,1.531,0.667,0.317,0.235,0.038
83,84,North Macedonia,5.274,0.983,1.294,0.838,0.345,0.185,0.034
84,85,Nigeria,5.265,0.696,1.111,0.245,0.426,0.215,0.041
85,86,Kyrgyzstan,5.261,0.551,1.438,0.723,0.508,0.300,0.023
86,87,Turkmenistan,5.247,1.052,1.538,0.657,0.394,0.244,0.028
87,88,Algeria,5.211,1.002,1.160,0.785,0.086,0.073,0.114
88,89,Morocco,5.208,0.801,0.782,0.782,0.418,0.036,0.076
89,90,Azerbaijan,5.208,1.043,1.147,0.769,0.351,0.035,0.182
90,91,Lebanon,5.197,0.987,1.224,0.815,0.216,0.166,0.027
91,92,Indonesia,5.192,0.931,1.203,0.660,0.491,0.498,0.028
92,93,China,5.191,1.029,1.125,0.893,0.521,0.058,0.100
93,94,Vietnam,5.175,0.741,1.346,0.851,0.543,0.147,0.073
94,95,Bhutan,5.082,0.813,1.321,0.604,0.457,0.370,0.167
95,96,Cameroon,5.044,0.549,0.910,0.331,0.381,0.187,0.037
96,97,Bulgaria,5.011,1.092,1.513,0.815,0.311,0.081,0.004
97,98,Ghana,4.996,0.611,0.868,0.486,0.381,0.245,0.040
98,99,Ivory Coast,4.944,0.569,0.808,0.232,0.352,0.154,0.090
99,100,Nepal,4.913,0.446,1.226,0.677,0.439,0.285,0.089
100,101,Jordan,4.906,0.837,1.225,0.815,0.383,0.110,0.130
101,102,Benin,4.883,0.393,0.437,0.397,0.349,0.175,0.082
102,103,Congo (Brazzaville),4.812,0.673,0.799,0.508,0.372,0.105,0.093
103,104,Gabon,4.799,1.057,1.183,0.571,0.295,0.043,0.055
104,105,Laos,4.796,0.764,1.030,0.551,0.547,0.266,0.164
105,106,South Africa,4.722,0.960,1.351,0.469,0.389,0.130,0.055
106,107,Albania,4.719,0.947,0.848,0.874,0.383,0.178,0.027
107,108,Venezuela,4.707,0.960,1.427,0.805,0.154,0.064,0.047
108,109,Cambodia,4.700,0.574,1.122,0.637,0.609,0.232,0.062
109,110,Palestinian Territories,4.696,0.657,1.247,0.672,0.225,0.103,0.066
110,111,Senegal,4.681,0.450,1.134,0.571,0.292,0.153,0.072
111,112,Somalia,4.668,0.000,0.698,0.268,0.559,0.243,0.270
112,113,Namibia,4.639,0.879,1.313,0.477,0.401,0.070,0.056
113,114,Niger,4.628,0.138,0.774,0.366,0.318,0.188,0.102
114,115,Burkina Faso,4.587,0.331,1.056,0.380,0.255,0.177,0.113
115,116,Armenia,4.559,0.850,1.055,0.815,0.283,0.095,0.064
116,117,Iran,4.548,1.100,0.842,0.785,0.305,0.270,0.125
117,118,Guinea,4.534,0.380,0.829,0.375,0.332,0.207,0.086
118,119,Georgia,4.519,0.886,0.666,0.752,0.346,0.043,0.164
119,120,Gambia,4.516,0.308,0.939,0.428,0.382,0.269,0.167
120,121,Kenya,4.509,0.512,0.983,0.581,0.431,0.372,0.053
121,122,Mauritania,4.490,0.570,1.167,0.489,0.066,0.106,0.088
122,123,Mozambique,4.466,0.204,0.986,0.390,0.494,0.197,0.138
123,124,Tunisia,4.461,0.921,1.000,0.815,0.167,0.059,0.055
124,125,Bangladesh,4.456,0.562,0.928,0.723,0.527,0.166,0.143
125,126,Iraq,4.437,1.043,0.980,0.574,0.241,0.148,0.089
126,127,Congo (Kinshasa),4.418,0.094,1.125,0.357,0.269,0.212,0.053
127,128,Mali,4.390,0.385,1.105,0.308,0.327,0.153,0.052
128,129,Sierra Leone,4.374,0.268,0.841,0.242,0.309,0.252,0.045
129,130,Sri Lanka,4.366,0.949,1.265,0.831,0.470,0.244,0.047
130,131,Myanmar,4.360,0.710,1.181,0.555,0.525,0.566,0.172
131,132,Chad,4.350,0.350,0.766,0.192,0.174,0.198,0.078
132,133,Ukraine,4.332,0.820,1.390,0.739,0.178,0.187,0.010
133,134,Ethiopia,4.286,0.336,1.033,0.532,0.344,0.209,0.100
134,135,Swaziland,4.212,0.811,1.149,0.000,0.313,0.074,0.135
135,136,Uganda,4.189,0.332,1.069,0.443,0.356,0.252,0.060
136,137,Egypt,4.166,0.913,1.039,0.644,0.241,0.076,0.067
137,138,Zambia,4.107,0.578,1.058,0.426,0.431,0.247,0.087
138,139,Togo,4.085,0.275,0.572,0.410,0.293,0.177,0.085
139,140,India,4.015,0.755,0.765,0.588,0.498,0.200,0.085
140,141,Liberia,3.975,0.073,0.922,0.443,0.370,0.233,0.033
141,142,Comoros,3.973,0.274,0.757,0.505,0.142,0.275,0.078
142,143,Madagascar,3.933,0.274,0.916,0.555,0.148,0.169,0.041
143,144,Lesotho,3.802,0.489,1.169,0.168,0.359,0.107,0.093
144,145,Burundi,3.775,0.046,0.447,0.380,0.220,0.176,0.180
145,146,Zimbabwe,3.663,0.366,1.114,0.433,0.361,0.151,0.089
146,147,Haiti,3.597,0.323,0.688,0.449,0.026,0.419,0.110
147,148,Botswana,3.488,1.041,1.145,0.538,0.455,0.025,0.100
148,149,Syria,3.462,0.619,0.378,0.440,0.013,0.331,0.141
149,150,Malawi,3.410,0.191,0.560,0.495,0.443,0.218,0.089
150,151,Yemen,3.380,0.287,1.163,0.463,0.143,0.108,0.077
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [7]:
#Checking the missing columns of the df
for year in years:
    print(f"""{year} \n{df[year].shape}
----------""")

2015
(158, 10)
----------
2016
(157, 10)
----------
2017
(155, 10)
----------
2018
(156, 9)
----------
2019
(156, 9)
----------

In [8]:
#Calculating the missing dystopian columnn values for 2018 and 2019 and Renaming the columns over that period
for year in years[-2:]:
    df[year]['Dystopia_Residual'] = df[year].loc[:,'Score']-df[year].loc[:,'GDP_per_capita':].sum(axis=1)
    df[year].rename(columns={
    'Score':'Happiness_Score',
    'GDP_per_capita':'Economy_(GDP_per_Capita)',
    'Social_support':'Family',
    'Healthy_life_expectancy':'Health_(Life_Expectancy)',
    'Freedom_to_make_life_choices':'Freedom',
    'Perceptions_of_corruption':'Trust_(Government_Corruption)',
    'Overall_rank':'Happiness_Rank',
    'Country_or_region':'Country'
 },inplace=True)
    
#Renaming 2017 df column names
df[2017].rename(columns={
    'Happiness.Score':'Happiness_Score',
    'Economy..GDP.per.Capita.':'Economy_(GDP_per_Capita)',
    'Health..Life.Expectancy.':'Health_(Life_Expectancy)',
    'Trust..Government.Corruption.':'Trust_(Government_Corruption)',
    'Happiness.Rank':'Happiness_Rank',
    'Dystopia.Residual':'Dystopia_Residual'
 },inplace=True)

In [9]:
#Showing all the columns of the df are equal size
for year in years:
    print(f"""{year} \n{df[year].shape}
----------""")

2015
(158, 10)
----------
2016
(157, 10)
----------
2017
(155, 10)
----------
2018
(156, 10)
----------
2019
(156, 10)
----------

In [10]:
#Finding any duplicates in df
for year in years:
    print(f"""{year} \n{df[year]['Country'].nunique()}
----------""")

2015
158
----------
2016
157
----------
2017
155
----------
2018
156
----------
2019
156
----------

In [11]:
#Checking if the right data type in data frames 
for year in years:
    print(f"""\n{year} \n{df[year].info()}
----------\n""")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Happiness_Rank                 158 non-null    int64
 2   Happiness_Score                158 non-null    float64
 3   Economy_(GDP_per_Capita)       158 non-null    float64
 4   Family                         158 non-null    float64
 5   Health_(Life_Expectancy)       158 non-null    float64
 6   Freedom                        158 non-null    float64
 7   Trust_(Government_Corruption)  158 non-null    float64
 8   Generosity                     158 non-null    float64
 9   Dystopia_Residual              158 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 12.5+ KB

2015
None
----------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Happiness_Rank                 157 non-null    int64
 2   Happiness_Score                157 non-null    float64
 3   Economy_(GDP_per_Capita)       157 non-null    float64
 4   Family                         157 non-null    float64
 5   Health_(Life_Expectancy)       157 non-null    float64
 6   Freedom                        157 non-null    float64
 7   Trust_(Government_Corruption)  157 non-null    float64
 8   Generosity                     157 non-null    float64
 9   Dystopia_Residual              157 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 12.4+ KB

2016
None
----------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness_Rank                 155 non-null    int64
 2   Happiness_Score                155 non-null    float64
 3   Economy_(GDP_per_Capita)       155 non-null    float64
 4   Family                         155 non-null    float64
 5   Health_(Life_Expectancy)       155 non-null    float64
 6   Freedom                        155 non-null    float64
 7   Generosity                     155 non-null    float64
 8   Trust_(Government_Corruption)  155 non-null    float64
 9   Dystopia_Residual              155 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 12.2+ KB

2017
None
----------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Happiness_Rank                 156 non-null    int64
 1   Country                        156 non-null    object
 2   Happiness_Score                156 non-null    float64
 3   Economy_(GDP_per_Capita)       156 non-null    float64
 4   Family                         156 non-null    float64
 5   Health_(Life_Expectancy)       156 non-null    float64
 6   Freedom                        156 non-null    float64
 7   Generosity                     156 non-null    float64
 8   Trust_(Government_Corruption)  156 non-null    float64
 9   Dystopia_Residual              156 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 12.3+ KB

2018
None
----------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Happiness_Rank                 156 non-null    int64
 1   Country                        156 non-null    object
 2   Happiness_Score                156 non-null    float64
 3   Economy_(GDP_per_Capita)       156 non-null    float64
 4   Family                         156 non-null    float64
 5   Health_(Life_Expectancy)       156 non-null    float64
 6   Freedom                        156 non-null    float64
 7   Generosity                     156 non-null    float64
 8   Trust_(Government_Corruption)  156 non-null    float64
 9   Dystopia_Residual              156 non-null    float64
dtypes: float64(8), int64(1), object(1)
memory usage: 12.3+ KB

2019
None
----------

In [12]:
for year in years:
    print(f"""\n{year} \n{df[year].columns}
----------\n""")

2015
Index(['Country', 'Happiness_Rank', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Trust_(Government_Corruption)', 'Generosity',
       'Dystopia_Residual'],
      dtype='object')
----------


2016
Index(['Country', 'Happiness_Rank', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Trust_(Government_Corruption)', 'Generosity',
       'Dystopia_Residual'],
      dtype='object')
----------


2017
Index(['Country', 'Happiness_Rank', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Generosity', 'Trust_(Government_Corruption)',
       'Dystopia_Residual'],
      dtype='object')
----------


2018
Index(['Happiness_Rank', 'Country', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Generosity', 'Trust_(Government_Corruption)',
       'Dystopia_Residual'],
      dtype='object')
----------


2019
Index(['Happiness_Rank', 'Country', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Generosity', 'Trust_(Government_Corruption)',
       'Dystopia_Residual'],
      dtype='object')
----------

# 1.2 Exporting the Cleaned Data

In [13]:
#Restructurin the column names for uniformity in df
#Writing the cleaned df into csv
for year in years:
    df[year] = df[year][['Country', 'Happiness_Rank', 'Happiness_Score',
       'Economy_(GDP_per_Capita)', 'Family', 'Health_(Life_Expectancy)',
       'Freedom', 'Trust_(Government_Corruption)', 'Generosity',
       'Dystopia_Residual']]
    df[year].to_csv(f"../Output/{year}.csv",index=False)

In [14]:
for year in years:
    df[year]['year'] = [year for x in range(len(df[year].Country))]

<ipython-input-14-7fa2ebca9261>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[year]['year'] = [year for x in range(len(df[year].Country))]

# 1.3 Exporting Caoncated Data
### Cancated CSV is used for plotly graphs with  to diplay year-slider

In [15]:
df_list = [df[x] for x in range(2015,2020)]
concated_df =  pd.concat(df_list)

In [16]:
#

In [17]:
concated_df.sort_values('Happiness_Rank',inplace=True)
concated_df.reset_index(drop=True,inplace=True)
concated_df.to_csv(f"../Output/concated_df.csv",index=False)
concated_df.head(50)

,Country,Happiness_Rank,Happiness_Score,Economy_(GDP_per_Capita),Family,Health_(Life_Expectancy),Freedom,Trust_(Government_Corruption),Generosity,Dystopia_Residual,year
0,Switzerland,1,7.587,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2.517380,2015
1,Finland,1,7.769,1.340000,1.587000,0.986000,0.596000,0.393000,0.153000,2.714000,2019
2,Finland,1,7.632,1.305000,1.592000,0.874000,0.681000,0.393000,0.202000,2.585000,2018
3,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027,2017
4,Denmark,1,7.526,1.441780,1.163740,0.795040,0.579410,0.444530,0.361710,2.739390,2016
5,Norway,2,7.594,1.456000,1.582000,0.861000,0.686000,0.340000,0.286000,2.383000,2018
6,Switzerland,2,7.509,1.527330,1.145240,0.863030,0.585570,0.412030,0.280830,2.694630,2016
7,Iceland,2,7.561,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2.702010,2015
8,Denmark,2,7.600,1.383000,1.573000,0.996000,0.592000,0.410000,0.252000,2.394000,2019
9,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707,2017
10,Iceland,3,7.501,1.426660,1.183260,0.867330,0.566240,0.149750,0.476780,2.831370,2016
11,Denmark,3,7.555,1.351000,1.590000,0.868000,0.683000,0.408000,0.284000,2.371000,2018
12,Denmark,3,7.527,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2.492040,2015
13,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715,2017
14,Norway,3,7.554,1.488000,1.582000,1.028000,0.603000,0.341000,0.271000,2.241000,2019
15,Norway,4,7.522,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2.465310,2015
16,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716,2017
17,Iceland,4,7.494,1.380000,1.624000,1.026000,0.591000,0.118000,0.354000,2.401000,2019
18,Norway,4,7.498,1.577440,1.126900,0.795790,0.596090,0.357760,0.378950,2.664650,2016
19,Iceland,4,7.495,1.343000,1.644000,0.914000,0.677000,0.138000,0.353000,2.426000,2018
20,Canada,5,7.427,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2.451760,2015
21,Netherlands,5,7.488,1.396000,1.522000,0.999000,0.557000,0.298000,0.322000,2.394000,2019
22,Finland,5,7.413,1.405980,1.134640,0.810910,0.571040,0.410040,0.254920,2.825960,2016
23,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182,2017
24,Switzerland,5,7.487,1.420000,1.549000,0.927000,0.660000,0.357000,0.256000,2.318000,2018
25,Canada,6,7.404,1.440150,1.096100,0.827600,0.573700,0.313290,0.448340,2.704850,2016
26,Netherlands,6,7.377,1.503945,1.428939,0.810696,0.585384,0.282662,0.470490,2.294804,2017
27,Finland,6,7.406,1.290250,1.318260,0.889110,0.641690,0.413720,0.233510,2.619550,2015
28,Switzerland,6,7.480,1.452000,1.526000,1.052000,0.572000,0.343000,0.263000,2.272000,2019
29,Netherlands,6,7.441,1.361000,1.488000,0.878000,0.638000,0.295000,0.333000,2.448000,2018
30,Netherlands,7,7.378,1.329440,1.280170,0.892840,0.615760,0.318140,0.476100,2.465700,2015
31,Canada,7,7.316,1.479204,1.481349,0.834558,0.611101,0.287372,0.435540,2.187264,2017
32,Sweden,7,7.343,1.387000,1.487000,1.009000,0.574000,0.373000,0.267000,2.246000,2019
33,Netherlands,7,7.339,1.464680,1.029120,0.812310,0.552110,0.299270,0.474160,2.707490,2016
34,Canada,7,7.328,1.330000,1.532000,0.896000,0.653000,0.291000,0.321000,2.305000,2018
35,New Zealand,8,7.324,1.268000,1.601000,0.876000,0.669000,0.389000,0.365000,2.156000,2018
36,New Zealand,8,7.314,1.405706,1.548195,0.816760,0.614062,0.382817,0.500005,2.046456,2017
37,New Zealand,8,7.334,1.360660,1.172780,0.830960,0.581470,0.419040,0.494010,2.475530,2016
38,New Zealand,8,7.307,1.303000,1.557000,1.026000,0.585000,0.380000,0.330000,2.126000,2019
39,Sweden,8,7.364,1.331710,1.289070,0.910870,0.659800,0.438440,0.362620,2.371190,2015
40,Australia,9,7.313,1.444430,1.104760,0.851200,0.568370,0.323310,0.474070,2.546500,2016
41,Sweden,9,7.284,1.494387,1.478162,0.830875,0.612924,0.384399,0.385399,2.097538,2017
42,Sweden,9,7.314,1.355000,1.501000,0.913000,0.659000,0.383000,0.285000,2.218000,2018
43,Canada,9,7.278,1.365000,1.505000,1.039000,0.584000,0.308000,0.285000,2.192000,2019
44,New Zealand,9,7.286,1.250180,1.319670,0.908370,0.639380,0.429220,0.475010,2.264250,2015
45,Austria,10,7.246,1.376000,1.475000,1.016000,0.532000,0.226000,0.244000,2.377000,2019
46,Australia,10,7.272,1.340000,1.573000,0.910000,0.647000,0.302000,0.361000,2.139000,2018
47,Sweden,10,7.291,1.451810,1.087640,0.831210,0.582180,0.408670,0.382540,2.547340,2016
48,Australia,10,7.284,1.333580,1.309230,0.931560,0.651240,0.356370,0.435620,2.266460,2015
49,Australia,10,7.284,1.484415,1.510042,0.843887,0.601607,0.301184,0.477699,2.065211,2017

# 1.4 Merging the Data

In [18]:
for year in years:
    print(f"{year} Total Countries: {df[year]['Country'].count()}   Last Rank is:  {df[year]['Happiness_Rank'].max()}")

2015 Total Countries: 158   Last Rank is:  158
2016 Total Countries: 157   Last Rank is:  157
2017 Total Countries: 155   Last Rank is:  155
2018 Total Countries: 156   Last Rank is:  156
2019 Total Countries: 156   Last Rank is:  156

In [19]:
# Merging all data frames into one data frame on Country column
merge_df = df_2015.merge(df_2016, on=['Country'], how='outer', suffixes=['_2015','_2016'])
merge_df = merge_df.merge(df_2017, on=['Country'], how='outer')
merge_df = merge_df.merge(df_2018, on=['Country'], how='outer', suffixes=['_2017','_2018'])
merge_df = merge_df.merge(df_2019, on=['Country'], how='outer')

# Adding suffix to 2019 columns
merge_df = merge_df.rename(columns={"Happiness_Rank": "Happiness_Rank_2019",
                                    "Happiness_Score": "Happiness_Score_2019",
                                    "Economy_(GDP_per_Capita)": "Economy_(GDP_per_Capita)_2019",
                                    "Family": "Family_2019",
                                    "Health_(Life_Expectancy)": "Health_(Life_Expectancy)_2019",
                                    "Trust_(Government_Corruption)": "Trust_(Government Corruption)_2019",
                                    "Freedom": "Freedom_2019",
                                    "Generosity": "Generosity_2019",
                                    "Dystopia_Residual": "Dystopia_Residual_2019"
                                   })

merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 170 entries, 0 to 169
Data columns (total 46 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             170 non-null    object
 1   Happiness_Rank_2015                 158 non-null    float64
 2   Happiness_Score_2015                158 non-null    float64
 3   Economy_(GDP_per_Capita)_2015       158 non-null    float64
 4   Family_2015                         158 non-null    float64
 5   Health_(Life_Expectancy)_2015       158 non-null    float64
 6   Freedom_2015                        158 non-null    float64
 7   Trust_(Government_Corruption)_2015  158 non-null    float64
 8   Generosity_2015                     158 non-null    float64
 9   Dystopia_Residual_2015              158 non-null    float64
 10  Happiness_Rank_2016                 157 non-null    float64
 11  Happiness_Score_2016                157 non-null    float64
 12  Economy_(GDP_per_Capita)_2016       157 non-null    float64
 13  Family_2016                         157 non-null    float64
 14  Health_(Life_Expectancy)_2016       157 non-null    float64
 15  Freedom_2016                        157 non-null    float64
 16  Trust_(Government_Corruption)_2016  157 non-null    float64
 17  Generosity_2016                     157 non-null    float64
 18  Dystopia_Residual_2016              157 non-null    float64
 19  Happiness_Rank_2017                 155 non-null    float64
 20  Happiness_Score_2017                155 non-null    float64
 21  Economy_(GDP_per_Capita)_2017       155 non-null    float64
 22  Family_2017                         155 non-null    float64
 23  Health_(Life_Expectancy)_2017       155 non-null    float64
 24  Freedom_2017                        155 non-null    float64
 25  Generosity_2017                     155 non-null    float64
 26  Trust_(Government_Corruption)_2017  155 non-null    float64
 27  Dystopia_Residual_2017              155 non-null    float64
 28  Happiness_Rank_2018                 156 non-null    float64
 29  Happiness_Score_2018                156 non-null    float64
 30  Economy_(GDP_per_Capita)_2018       156 non-null    float64
 31  Family_2018                         156 non-null    float64
 32  Health_(Life_Expectancy)_2018       156 non-null    float64
 33  Freedom_2018                        156 non-null    float64
 34  Generosity_2018                     156 non-null    float64
 35  Trust_(Government_Corruption)_2018  156 non-null    float64
 36  Dystopia_Residual_2018              156 non-null    float64
 37  Happiness_Rank_2019                 156 non-null    float64
 38  Happiness_Score_2019                156 non-null    float64
 39  Economy_(GDP_per_Capita)_2019       156 non-null    float64
 40  Family_2019                         156 non-null    float64
 41  Health_(Life_Expectancy)_2019       156 non-null    float64
 42  Freedom_2019                        156 non-null    float64
 43  Generosity_2019                     156 non-null    float64
 44  Trust_(Government Corruption)_2019  156 non-null    float64
 45  Dystopia_Residual_2019              156 non-null    float64
dtypes: float64(45), object(1)
memory usage: 62.4+ KB

In [20]:
# Checking for countries that has records in 2015, but not in 2016
df_2015[~df_2015.Country.isin(df_2016.Country)]

,Country,Happiness_Rank,Happiness_Score,Economy_(GDP_per_Capita),Family,Health_(Life_Expectancy),Freedom,Trust_(Government_Corruption),Generosity,Dystopia_Residual
21,Oman,22,6.853,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489
90,Somaliland region,91,5.057,0.18847,0.95152,0.43873,0.46582,0.39928,0.50318,2.11032
93,Mozambique,94,4.971,0.08308,1.02626,0.09131,0.34037,0.15603,0.22269,3.05137
96,Lesotho,97,4.898,0.37545,1.04103,0.07612,0.31767,0.12504,0.16388,2.79832
100,Swaziland,101,4.867,0.71206,1.07284,0.07566,0.30658,0.03060,0.18259,2.48676
125,Djibouti,126,4.369,0.44025,0.59207,0.36291,0.46074,0.28105,0.18093,2.05125
147,Central African Republic,148,3.678,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230

In [21]:
# Checking for countries that has records in 2016, but not in 2015
df_2016[~df_2016.Country.isin(df_2015.Country)]

,Country,Happiness_Rank,Happiness_Score,Economy_(GDP_per_Capita),Family,Health_(Life_Expectancy),Freedom,Trust_(Government_Corruption),Generosity,Dystopia_Residual
14,Puerto Rico,15,7.039,1.35943,1.08113,0.77758,0.46823,0.12275,0.22202,3.00760
51,Belize,52,5.956,0.87616,0.68655,0.45569,0.51231,0.10771,0.23684,3.08039
75,Somalia,76,5.440,0.00000,0.33613,0.11466,0.56778,0.31180,0.27225,3.83772
96,Somaliland Region,97,5.057,0.25558,0.75862,0.33108,0.39130,0.36794,0.51479,2.43801
112,Namibia,113,4.574,0.93287,0.70362,0.34745,0.48614,0.10398,0.07795,1.92198
142,South Sudan,143,3.832,0.39394,0.18519,0.15781,0.19662,0.13015,0.25899,2.50929

In [22]:
# Checking for countries that has records in later years but not in 2015
merge_df[~merge_df.Country.isin(df_2015.Country)]

,Country,Happiness_Rank_2015,Happiness_Score_2015,Economy_(GDP_per_Capita)_2015,Family_2015,Health_(Life_Expectancy)_2015,Freedom_2015,Trust_(Government_Corruption)_2015,Generosity_2015,Dystopia_Residual_2015,...,Dystopia_Residual_2018,Happiness_Rank_2019,Happiness_Score_2019,Economy_(GDP_per_Capita)_2019,Family_2019,Health_(Life_Expectancy)_2019,Freedom_2019,Generosity_2019,Trust_(Government Corruption)_2019,Dystopia_Residual_2019
158,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Somalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.961,112.0,4.668,0.000,0.698,0.268,0.559,0.243,0.270,2.630
161,Somaliland Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.287,113.0,4.639,0.879,1.313,0.477,0.401,0.070,0.056,1.443
163,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.690,156.0,2.853,0.306,0.575,0.295,0.010,0.202,0.091,1.374
164,Taiwan Province of China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,"Hong Kong S.A.R., China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,Trinidad & Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.148,39.0,6.192,1.231,1.477,0.713,0.489,0.185,0.016,2.081
167,Northern Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.658,64.0,5.718,1.263,1.252,1.042,0.417,0.191,0.162,1.391
168,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,84.0,5.274,0.983,1.294,0.838,0.345,0.185,0.034,1.595
169,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,120.0,4.516,0.308,0.939,0.428,0.382,0.269,0.167,2.023

In [23]:
# Replacing null value found in merged dataframe with 0
merge_df.fillna(0,inplace = True)
merge_df.isna().sum()

Country                               0
Happiness_Rank_2015                   0
Happiness_Score_2015                  0
Economy_(GDP_per_Capita)_2015         0
Family_2015                           0
Health_(Life_Expectancy)_2015         0
Freedom_2015                          0
Trust_(Government_Corruption)_2015    0
Generosity_2015                       0
Dystopia_Residual_2015                0
Happiness_Rank_2016                   0
Happiness_Score_2016                  0
Economy_(GDP_per_Capita)_2016         0
Family_2016                           0
Health_(Life_Expectancy)_2016         0
Freedom_2016                          0
Trust_(Government_Corruption)_2016    0
Generosity_2016                       0
Dystopia_Residual_2016                0
Happiness_Rank_2017                   0
Happiness_Score_2017                  0
Economy_(GDP_per_Capita)_2017         0
Family_2017                           0
Health_(Life_Expectancy)_2017         0
Freedom_2017                          0
Generosity_2017                       0
Trust_(Government_Corruption)_2017    0
Dystopia_Residual_2017                0
Happiness_Rank_2018                   0
Happiness_Score_2018                  0
Economy_(GDP_per_Capita)_2018         0
Family_2018                           0
Health_(Life_Expectancy)_2018         0
Freedom_2018                          0
Generosity_2018                       0
Trust_(Government_Corruption)_2018    0
Dystopia_Residual_2018                0
Happiness_Rank_2019                   0
Happiness_Score_2019                  0
Economy_(GDP_per_Capita)_2019         0
Family_2019                           0
Health_(Life_Expectancy)_2019         0
Freedom_2019                          0
Generosity_2019                       0
Trust_(Government Corruption)_2019    0
Dystopia_Residual_2019                0
dtype: int64

In [24]:
# Checking the country names which are in Merged Data frame, but missing in any of the years data frames
merge_df["Country"].loc[(~merge_df["Country"].isin(df_2015["Country"])) | \
                        (~merge_df["Country"].isin(df_2016["Country"])) | \
                        (~merge_df["Country"].isin(df_2017["Country"])) | \
                        (~merge_df["Country"].isin(df_2018["Country"])) | \
                        (~merge_df["Country"].isin(df_2019["Country"]))
                       ].sort_values()

136                      Angola
159                      Belize
147    Central African Republic
139                     Comoros
125                    Djibouti
169                      Gambia
71                    Hong Kong
165     Hong Kong S.A.R., China
98                         Laos
96                      Lesotho
92                    Macedonia
93                   Mozambique
162                     Namibia
65                 North Cyprus
168             North Macedonia
167             Northern Cyprus
21                         Oman
158                 Puerto Rico
160                     Somalia
161           Somaliland Region
90            Somaliland region
163                 South Sudan
117                       Sudan
39                     Suriname
100                   Swaziland
37                       Taiwan
164    Taiwan Province of China
166           Trinidad & Tobago
40          Trinidad and Tobago
Name: Country, dtype: object

In [25]:
# Making the country names matching for those refering to the same country 
merge_df["Country"].loc[merge_df.Country == "North Cyprus"] = "Northern Cyprus"
merge_df["Country"].loc[merge_df.Country == "Hong Kong S.A.R., China"] = "Hong Kong"
merge_df["Country"].loc[merge_df.Country == "Taiwan Province of China"] = "Taiwan"
merge_df["Country"].loc[merge_df.Country == "Macedonia"] = "North Macedonia"
merge_df["Country"].loc[merge_df.Country == "Trinidad & Tobago"] = "Trinidad and Tobago"
merge_df["Country"].loc[merge_df.Country == "Somaliland region"] = "Somaliland Region"

# Checking the country names which were not present in any of the years data frames
country_check_list = merge_df["Country"].loc[(~merge_df["Country"].isin(df_2015["Country"])) | \
                                             (~merge_df["Country"].isin(df_2016["Country"])) | \
                                             (~merge_df["Country"].isin(df_2017["Country"])) | \
                                             (~merge_df["Country"].isin(df_2018["Country"])) | \
                                             (~merge_df["Country"].isin(df_2019["Country"]))
                                            ].sort_values().tolist()
country_check_list = set(country_check_list)
country_check_list

C:\Users\bimal\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

{'Angola',
 'Belize',
 'Central African Republic',
 'Comoros',
 'Djibouti',
 'Gambia',
 'Hong Kong',
 'Laos',
 'Lesotho',
 'Mozambique',
 'Namibia',
 'North Macedonia',
 'Northern Cyprus',
 'Oman',
 'Puerto Rico',
 'Somalia',
 'Somaliland Region',
 'South Sudan',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Taiwan',
 'Trinidad and Tobago'}

In [26]:
# Displaying the list of Countries missing data in some year
merge_df.loc[merge_df["Country"].isin(country_check_list)]

,Country,Happiness_Rank_2015,Happiness_Score_2015,Economy_(GDP_per_Capita)_2015,Family_2015,Health_(Life_Expectancy)_2015,Freedom_2015,Trust_(Government_Corruption)_2015,Generosity_2015,Dystopia_Residual_2015,...,Dystopia_Residual_2018,Happiness_Rank_2019,Happiness_Score_2019,Economy_(GDP_per_Capita)_2019,Family_2019,Health_(Life_Expectancy)_2019,Freedom_2019,Generosity_2019,Trust_(Government Corruption)_2019,Dystopia_Residual_2019
21,Oman,22.0,6.853,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
37,Taiwan,38.0,6.298,1.29098,1.07617,0.87530,0.39740,0.08129,0.25376,2.32323,...,2.136,25.0,6.446,1.368,1.430,0.914,0.351,0.242,0.097,2.044
39,Suriname,40.0,6.269,0.99534,0.97200,0.60820,0.59657,0.13633,0.16991,2.79094,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
40,Trinidad and Tobago,41.0,6.168,1.21183,1.18354,0.61483,0.55884,0.01140,0.31844,2.26882,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
65,Northern Cyprus,66.0,5.695,1.20806,1.07008,0.92356,0.49027,0.14280,0.26169,1.59888,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
71,Hong Kong,72.0,5.474,1.38604,1.05818,1.01328,0.59608,0.37124,0.39478,0.65429,...,0.644,76.0,5.430,1.438,1.277,1.122,0.440,0.258,0.287,0.608
90,Somaliland Region,91.0,5.057,0.18847,0.95152,0.43873,0.46582,0.39928,0.50318,2.11032,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
92,North Macedonia,93.0,5.007,0.91851,1.00232,0.73545,0.33457,0.05327,0.22359,1.73933,...,1.677,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
93,Mozambique,94.0,4.971,0.08308,1.02626,0.09131,0.34037,0.15603,0.22269,3.05137,...,2.249,123.0,4.466,0.204,0.986,0.390,0.494,0.197,0.138,2.057
96,Lesotho,97.0,4.898,0.37545,1.04103,0.07612,0.31767,0.12504,0.16388,2.79832,...,1.391,144.0,3.802,0.489,1.169,0.168,0.359,0.107,0.093,1.417
98,Laos,99.0,4.876,0.59066,0.73803,0.54909,0.59591,0.24249,0.42192,1.73799,...,1.398,105.0,4.796,0.764,1.030,0.551,0.547,0.266,0.164,1.474
100,Swaziland,101.0,4.867,0.71206,1.07284,0.07566,0.30658,0.03060,0.18259,2.48676,...,0.000,135.0,4.212,0.811,1.149,0.000,0.313,0.074,0.135,1.730
117,Sudan,118.0,4.550,0.52107,1.01404,0.36878,0.10081,0.14660,0.19062,2.20857,...,1.750,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
125,Djibouti,126.0,4.369,0.44025,0.59207,0.36291,0.46074,0.28105,0.18093,2.05125,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
136,Angola,137.0,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939,...,1.531,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
139,Comoros,140.0,3.956,0.23906,0.79273,0.36315,0.22917,0.19900,0.17441,1.95812,...,0.000,142.0,3.973,0.274,0.757,0.505,0.142,0.275,0.078,1.942
147,Central African Republic,148.0,3.678,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230,...,2.488,155.0,3.083,0.026,0.000,0.105,0.225,0.235,0.035,2.457
158,Puerto Rico,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
159,Belize,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,2.709,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
160,Somalia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,2.961,112.0,4.668,0.000,0.698,0.268,0.559,0.243,0.270,2.630
161,Somaliland Region,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
162,Namibia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,1.287,113.0,4.639,0.879,1.313,0.477,0.401,0.070,0.056,1.443
163,South Sudan,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,1.690,156.0,2.853,0.306,0.575,0.295,0.010,0.202,0.091,1.374
164,Taiwan,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
165,Hong Kong,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
166,Trinidad and Tobago,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,2.148,39.0,6.192,1.231,1.477,0.713,0.489,0.185,0.016,2.081
167,Northern Cyprus,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,1.658,64.0,5.718,1.263,1.252,1.042,0.417,0.191,0.162,1.391
168,North Macedonia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,84.0,5.274,0.983,1.294,0.838,0.345,0.185,0.034,1.595
169,Gambia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,120.0,4.516,0.308,0.939,0.428,0.382,0.269,0.167,2.023

In [27]:
# Creating a list of country names duplicated
dup_countries = merge_df['Country'].loc[merge_df['Country'].duplicated()].tolist() 
dup_countries

['Somaliland Region',
 'Taiwan',
 'Hong Kong',
 'Trinidad and Tobago',
 'Northern Cyprus',
 'North Macedonia']

In [28]:
# Merging duplicate country names row wise by getting sum of each column values

# Loop through each duplicated country names in the list
for country in dup_countries:
    
    # Making a new data frame having only the duplicated country names
    joined_rows = merge_df.loc[merge_df.Country == country]
    # Adding a row to the new data frame with the sum of each columns
    joined_rows.loc[country,:] = joined_rows.sum(axis=0)
    # Correcting the Country column value
    joined_rows['Country'] = country
    
    # Removing those rows from the merged data frame
    merge_df.drop(merge_df[merge_df.Country == country].index, inplace=True)
    # Concatenating the last row added(sum) to the original merged data frame
    merge_df = pd.concat([merge_df, joined_rows.tail(1)])

# Reseting the merged data frame's index
merge_df.reset_index(drop=True, inplace=True)

# Displaying the countries data which were missing in any of the year's data frame - after cleaning
merge_df.loc[merge_df["Country"].isin(country_check_list)]

<ipython-input-28-482bab1ea765>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined_rows.loc[country,:] = joined_rows.sum(axis=0)

,Country,Happiness_Rank_2015,Happiness_Score_2015,Economy_(GDP_per_Capita)_2015,Family_2015,Health_(Life_Expectancy)_2015,Freedom_2015,Trust_(Government_Corruption)_2015,Generosity_2015,Dystopia_Residual_2015,...,Dystopia_Residual_2018,Happiness_Rank_2019,Happiness_Score_2019,Economy_(GDP_per_Capita)_2019,Family_2019,Health_(Life_Expectancy)_2019,Freedom_2019,Generosity_2019,Trust_(Government Corruption)_2019,Dystopia_Residual_2019
21,Oman,22.0,6.853,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
38,Suriname,40.0,6.269,0.99534,0.97200,0.60820,0.59657,0.13633,0.16991,2.79094,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
87,Mozambique,94.0,4.971,0.08308,1.02626,0.09131,0.34037,0.15603,0.22269,3.05137,...,2.249,123.0,4.466,0.204,0.986,0.390,0.494,0.197,0.138,2.057
90,Lesotho,97.0,4.898,0.37545,1.04103,0.07612,0.31767,0.12504,0.16388,2.79832,...,1.391,144.0,3.802,0.489,1.169,0.168,0.359,0.107,0.093,1.417
92,Laos,99.0,4.876,0.59066,0.73803,0.54909,0.59591,0.24249,0.42192,1.73799,...,1.398,105.0,4.796,0.764,1.030,0.551,0.547,0.266,0.164,1.474
94,Swaziland,101.0,4.867,0.71206,1.07284,0.07566,0.30658,0.03060,0.18259,2.48676,...,0.000,135.0,4.212,0.811,1.149,0.000,0.313,0.074,0.135,1.730
111,Sudan,118.0,4.550,0.52107,1.01404,0.36878,0.10081,0.14660,0.19062,2.20857,...,1.750,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
119,Djibouti,126.0,4.369,0.44025,0.59207,0.36291,0.46074,0.28105,0.18093,2.05125,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
130,Angola,137.0,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939,...,1.531,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
133,Comoros,140.0,3.956,0.23906,0.79273,0.36315,0.22917,0.19900,0.17441,1.95812,...,0.000,142.0,3.973,0.274,0.757,0.505,0.142,0.275,0.078,1.942
141,Central African Republic,148.0,3.678,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230,...,2.488,155.0,3.083,0.026,0.000,0.105,0.225,0.235,0.035,2.457
152,Puerto Rico,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
153,Belize,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,2.709,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
154,Somalia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,2.961,112.0,4.668,0.000,0.698,0.268,0.559,0.243,0.270,2.630
155,Namibia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,1.287,113.0,4.639,0.879,1.313,0.477,0.401,0.070,0.056,1.443
156,South Sudan,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,1.690,156.0,2.853,0.306,0.575,0.295,0.010,0.202,0.091,1.374
157,Gambia,0.0,0.000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.000,120.0,4.516,0.308,0.939,0.428,0.382,0.269,0.167,2.023
158,Somaliland Region,91.0,5.057,0.18847,0.95152,0.43873,0.46582,0.39928,0.50318,2.11032,...,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
159,Taiwan,38.0,6.298,1.29098,1.07617,0.87530,0.39740,0.08129,0.25376,2.32323,...,2.136,25.0,6.446,1.368,1.430,0.914,0.351,0.242,0.097,2.044
160,Hong Kong,72.0,5.474,1.38604,1.05818,1.01328,0.59608,0.37124,0.39478,0.65429,...,0.644,76.0,5.430,1.438,1.277,1.122,0.440,0.258,0.287,0.608
161,Trinidad and Tobago,41.0,6.168,1.21183,1.18354,0.61483,0.55884,0.01140,0.31844,2.26882,...,2.148,39.0,6.192,1.231,1.477,0.713,0.489,0.185,0.016,2.081
162,Northern Cyprus,66.0,5.695,1.20806,1.07008,0.92356,0.49027,0.14280,0.26169,1.59888,...,1.658,64.0,5.718,1.263,1.252,1.042,0.417,0.191,0.162,1.391
163,North Macedonia,93.0,5.007,0.91851,1.00232,0.73545,0.33457,0.05327,0.22359,1.73933,...,1.677,84.0,5.274,0.983,1.294,0.838,0.345,0.185,0.034,1.595

In [29]:
# Replacing 0 values with NAN
cols = merge_df.columns
merge_df[cols] = merge_df[cols].replace({'0':np.nan, 0:np.nan})

merge_df.sort_values

# Writing the cleaned merged data frame to a csv file
merge_df.to_csv("../Output/happiness_merged.csv", index=False)

### Getting Region data using API

In [30]:
# Loading data from merged csv
df = pd.read_csv("../Output/happiness_merged.csv")

# URL for GET requests to retrieve Region data of Countries from Rest Countries API
base_url = "https://restcountries.eu/rest/v2/name/"

In [31]:
# Defining a function to fetch each Contries Region with API
def fetchRegion(countries):

    country_list = []
    region_list = []
    not_found = []

    for country in countries:
        try:   
            # Appending country name to the base url
            url = f"{base_url}{country}"

            # Perform a get request for each country
            response = requests.get(url)

            # Storing the JSON response within a variable
            data = response.json()
            
            # Adding the region and country name to lists
            region_list.append(data[0]['region'])
            country_list.append(country)

        except:
            not_found.append(country)
    # function return all the list of values
    return country_list, region_list, not_found

In [32]:
# Creating a list of all countries from each years data
countries = df['Country']

# Calling out the function to fetch regions of countries in countries list
country_list, region_list, not_found = fetchRegion(countries)

# Creating a data frame with the list values returned from the function
df_region = pd.DataFrame({"Country": country_list, "Region": region_list})

print(f"Countries Not Found: {not_found}")
df_region

Countries Not Found: ['South Korea', 'Palestinian Territories', 'Congo (Kinshasa)', 'Congo (Brazzaville)', 'Somaliland Region', 'Northern Cyprus', 'North Macedonia']

                      Country    Region
0                 Switzerland    Europe
1                     Iceland    Europe
2                     Denmark    Europe
3                      Norway    Europe
4                      Canada  Americas
5                     Finland    Europe
6                 Netherlands    Europe
7                      Sweden    Europe
8                 New Zealand   Oceania
9                   Australia   Oceania
10                     Israel      Asia
11                 Costa Rica  Americas
12                    Austria    Europe
13                     Mexico  Americas
14              United States  Americas
15                     Brazil  Americas
16                 Luxembourg    Europe
17                    Ireland    Europe
18                    Belgium    Europe
19       United Arab Emirates      Asia
20             United Kingdom    Europe
21                       Oman      Asia
22                  Venezuela  Americas
23                  Singapore      Asia
24                     Panama  Americas
25                    Germany    Europe
26                      Chile  Americas
27                      Qatar      Asia
28                     France    Europe
29                  Argentina  Americas
30             Czech Republic    Europe
31                    Uruguay  Americas
32                   Colombia  Americas
33                   Thailand      Asia
34               Saudi Arabia      Asia
35                      Spain    Europe
36                      Malta    Europe
37                     Kuwait      Asia
38                   Suriname  Americas
39                El Salvador  Americas
40                  Guatemala  Americas
41                 Uzbekistan      Asia
42                   Slovakia    Europe
43                      Japan      Asia
44                    Ecuador  Americas
45                    Bahrain      Asia
46                      Italy    Europe
47                    Bolivia  Americas
48                    Moldova    Europe
49                   Paraguay  Americas
50                 Kazakhstan      Asia
51                   Slovenia    Europe
52                  Lithuania    Europe
53                  Nicaragua  Americas
54                       Peru  Americas
55                    Belarus    Europe
56                     Poland    Europe
57                   Malaysia      Asia
58                    Croatia    Europe
59                      Libya    Africa
60                     Russia    Europe
61                    Jamaica  Americas
62                     Cyprus    Europe
63                    Algeria    Africa
64                     Kosovo    Europe
65               Turkmenistan      Asia
66                  Mauritius    Africa
67                    Estonia    Europe
68                  Indonesia      Asia
69                    Vietnam      Asia
70                     Turkey      Asia
71                 Kyrgyzstan      Asia
72                    Nigeria    Africa
73                     Bhutan      Asia
74                 Azerbaijan      Asia
75                   Pakistan      Asia
76                     Jordan      Asia
77                 Montenegro    Europe
78                      China      Asia
79                     Zambia    Africa
80                    Romania    Europe
81                     Serbia    Europe
82                   Portugal    Europe
83                     Latvia    Europe
84                Philippines      Asia
85                    Morocco    Africa
86                 Mozambique    Africa
87                    Albania    Europe
88     Bosnia and Herzegovina    Europe
89                    Lesotho    Africa
90         Dominican Republic  Americas
91                       Laos      Asia
92                   Mongolia      Asia
93                  Swaziland    Africa
94                     Greece    Europe
95                    Lebanon      Asia
96                    Hungary    Europe
97                   Honduras  Americas
98                 Tajikistan      Asia
99                    Tunisia    Africa
100                Bangladesh      Asia
101                      Iran      Asia
102                   Ukraine    Europe
103                      Iraq      Asia
104              South Africa    Africa
105                     Ghana    Africa
106                  Zimbabwe    Africa
107                   Liberia    Africa
108                     India    Africa
109                     Sudan    Africa
110                     Haiti  Americas
111                     Nepal      Asia
112                  Ethiopia    Africa
113              Sierra Leone    Africa
114                Mauritania    Africa
115                     Kenya    Africa
116                  Djibouti    Africa
117                   Armenia      Asia
118                  Botswana    Africa
119                   Myanmar      Asia
120                   Georgia      Asia
121                    Malawi    Africa
122                 Sri Lanka      Asia
123                  Cameroon    Africa
124                  Bulgaria    Europe
125                     Egypt    Africa
126                     Yemen      Asia
127                    Angola    Africa
128                      Mali    Africa
129                   Comoros    Africa
130                    Uganda    Africa
131                   Senegal    Africa
132                     Gabon    Africa
133                     Niger    Africa
134                  Cambodia      Asia
135                  Tanzania    Africa
136                Madagascar    Africa
137  Central African Republic    Africa
138                      Chad    Africa
139                    Guinea    Africa
140               Ivory Coast    Africa
141              Burkina Faso    Africa
142               Afghanistan      Asia
143                    Rwanda    Africa
144                     Benin    Africa
145                     Syria      Asia
146                   Burundi    Africa
147                      Togo    Africa
148               Puerto Rico  Americas
149                    Belize  Americas
150                   Somalia    Africa
151                   Namibia    Africa
152               South Sudan    Africa
153                    Gambia    Africa
154                    Taiwan      Asia
155                 Hong Kong      Asia
156       Trinidad and Tobago  Americas

In [33]:
# Getting region from nearby location or other name
df_not_found = pd.DataFrame({'Country': not_found,
                             'Try_Name':['Korea', 'Palestine',
                                         'Congo', 'Congo',
                                         'Somalia', 'Cyprus',
                                         'Macedonia']                              
                           })
df_not_found

                   Country   Try_Name
0              South Korea      Korea
1  Palestinian Territories  Palestine
2         Congo (Kinshasa)      Congo
3      Congo (Brazzaville)      Congo
4        Somaliland Region    Somalia
5          Northern Cyprus     Cyprus
6          North Macedonia  Macedonia

In [34]:
# Creating a new list of countries to fecth region which didn't get results yet
countries = df_not_found["Try_Name"].tolist()

# Calling out the function to fetch regions of countries in the new list
country_list, region_list, not_found = fetchRegion(countries)

# Creating a data frame with the list values returned from the function
df_found = pd.DataFrame({"Try_Name": country_list, "Region": region_list})

# Checking if any Country's Region is still missing
print(f"Number of Countries Not Found: {len(not_found)}")

df_found

Number of Countries Not Found: 0

    Try_Name  Region
0      Korea    Asia
1  Palestine    Asia
2      Congo  Africa
3      Congo  Africa
4    Somalia  Africa
5     Cyprus  Europe
6  Macedonia  Europe

In [35]:
# Merging The 2 data frames to eliminate Try_Name in between
merge_df = df_not_found.merge(df_found, on='Try_Name', how= 'left')
merge_df.drop(['Try_Name'], axis=1, inplace= True)
merge_df

                   Country  Region
0              South Korea    Asia
1  Palestinian Territories    Asia
2         Congo (Kinshasa)  Africa
3         Congo (Kinshasa)  Africa
4      Congo (Brazzaville)  Africa
5      Congo (Brazzaville)  Africa
6        Somaliland Region  Africa
7          Northern Cyprus  Europe
8          North Macedonia  Europe

In [36]:
# Concatenating the data frames with Country and Region found in 2 function calls
df_region = pd.concat([df_region, merge_df]).reset_index(drop=True)
df_region

                      Country    Region
0                 Switzerland    Europe
1                     Iceland    Europe
2                     Denmark    Europe
3                      Norway    Europe
4                      Canada  Americas
5                     Finland    Europe
6                 Netherlands    Europe
7                      Sweden    Europe
8                 New Zealand   Oceania
9                   Australia   Oceania
10                     Israel      Asia
11                 Costa Rica  Americas
12                    Austria    Europe
13                     Mexico  Americas
14              United States  Americas
15                     Brazil  Americas
16                 Luxembourg    Europe
17                    Ireland    Europe
18                    Belgium    Europe
19       United Arab Emirates      Asia
20             United Kingdom    Europe
21                       Oman      Asia
22                  Venezuela  Americas
23                  Singapore      Asia
24                     Panama  Americas
25                    Germany    Europe
26                      Chile  Americas
27                      Qatar      Asia
28                     France    Europe
29                  Argentina  Americas
30             Czech Republic    Europe
31                    Uruguay  Americas
32                   Colombia  Americas
33                   Thailand      Asia
34               Saudi Arabia      Asia
35                      Spain    Europe
36                      Malta    Europe
37                     Kuwait      Asia
38                   Suriname  Americas
39                El Salvador  Americas
40                  Guatemala  Americas
41                 Uzbekistan      Asia
42                   Slovakia    Europe
43                      Japan      Asia
44                    Ecuador  Americas
45                    Bahrain      Asia
46                      Italy    Europe
47                    Bolivia  Americas
48                    Moldova    Europe
49                   Paraguay  Americas
50                 Kazakhstan      Asia
51                   Slovenia    Europe
52                  Lithuania    Europe
53                  Nicaragua  Americas
54                       Peru  Americas
55                    Belarus    Europe
56                     Poland    Europe
57                   Malaysia      Asia
58                    Croatia    Europe
59                      Libya    Africa
60                     Russia    Europe
61                    Jamaica  Americas
62                     Cyprus    Europe
63                    Algeria    Africa
64                     Kosovo    Europe
65               Turkmenistan      Asia
66                  Mauritius    Africa
67                    Estonia    Europe
68                  Indonesia      Asia
69                    Vietnam      Asia
70                     Turkey      Asia
71                 Kyrgyzstan      Asia
72                    Nigeria    Africa
73                     Bhutan      Asia
74                 Azerbaijan      Asia
75                   Pakistan      Asia
76                     Jordan      Asia
77                 Montenegro    Europe
78                      China      Asia
79                     Zambia    Africa
80                    Romania    Europe
81                     Serbia    Europe
82                   Portugal    Europe
83                     Latvia    Europe
84                Philippines      Asia
85                    Morocco    Africa
86                 Mozambique    Africa
87                    Albania    Europe
88     Bosnia and Herzegovina    Europe
89                    Lesotho    Africa
90         Dominican Republic  Americas
91                       Laos      Asia
92                   Mongolia      Asia
93                  Swaziland    Africa
94                     Greece    Europe
95                    Lebanon      Asia
96                    Hungary    Europe
97                   Honduras  Americas
98                 Tajikistan      Asia
99                    Tunisia    Africa
100                Bangladesh      Asia
101                      Iran      Asia
102                   Ukraine    Europe
103                      Iraq      Asia
104              South Africa    Africa
105                     Ghana    Africa
106                  Zimbabwe    Africa
107                   Liberia    Africa
108                     India    Africa
109                     Sudan    Africa
110                     Haiti  Americas
111                     Nepal      Asia
112                  Ethiopia    Africa
113              Sierra Leone    Africa
114                Mauritania    Africa
115                     Kenya    Africa
116                  Djibouti    Africa
117                   Armenia      Asia
118                  Botswana    Africa
119                   Myanmar      Asia
120                   Georgia      Asia
121                    Malawi    Africa
122                 Sri Lanka      Asia
123                  Cameroon    Africa
124                  Bulgaria    Europe
125                     Egypt    Africa
126                     Yemen      Asia
127                    Angola    Africa
128                      Mali    Africa
129                   Comoros    Africa
130                    Uganda    Africa
131                   Senegal    Africa
132                     Gabon    Africa
133                     Niger    Africa
134                  Cambodia      Asia
135                  Tanzania    Africa
136                Madagascar    Africa
137  Central African Republic    Africa
138                      Chad    Africa
139                    Guinea    Africa
140               Ivory Coast    Africa
141              Burkina Faso    Africa
142               Afghanistan      Asia
143                    Rwanda    Africa
144                     Benin    Africa
145                     Syria      Asia
146                   Burundi    Africa
147                      Togo    Africa
148               Puerto Rico  Americas
149                    Belize  Americas
150                   Somalia    Africa
151                   Namibia    Africa
152               South Sudan    Africa
153                    Gambia    Africa
154                    Taiwan      Asia
155                 Hong Kong      Asia
156       Trinidad and Tobago  Americas
157               South Korea      Asia
158   Palestinian Territories      Asia
159          Congo (Kinshasa)    Africa
160          Congo (Kinshasa)    Africa
161       Congo (Brazzaville)    Africa
162       Congo (Brazzaville)    Africa
163         Somaliland Region    Africa
164           Northern Cyprus    Europe
165           North Macedonia    Europe

In [37]:
# Merging region with the happiness data frame
df = df_region.merge(df, on="Country", how="left")

# Writing the data back to the merge csv file
df.to_csv('../Output/happiness_merged.csv', index=False)

# 1.5 Suicide csv data cleaning

In [38]:
# Reading all the needed csv data into dataframes 
df = pd.read_csv("../Output/happiness_merged.csv")
df_suicide = pd.read_csv("../Resources/suicide_death_rate.csv", encoding='utf-8')

df.head()

,Country,Region,Happiness_Rank_2015,Happiness_Score_2015,Economy_(GDP_per_Capita)_2015,Family_2015,Health_(Life_Expectancy)_2015,Freedom_2015,Trust_(Government_Corruption)_2015,Generosity_2015,...,Dystopia_Residual_2018,Happiness_Rank_2019,Happiness_Score_2019,Economy_(GDP_per_Capita)_2019,Family_2019,Health_(Life_Expectancy)_2019,Freedom_2019,Generosity_2019,Trust_(Government Corruption)_2019,Dystopia_Residual_2019
0,Switzerland,Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,2.318,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343,2.272
1,Iceland,Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,2.426,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2.401
2,Denmark,Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,2.371,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2.394
3,Norway,Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,2.383,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2.241
4,Canada,Americas,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,2.305,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308,2.192

In [39]:
# Selecting the needed Columns and dropping the unnecessary from the happiness data frame
df = df.loc[:,['Country',
               'Region',
               'Happiness_Score_2015',
               'Happiness_Score_2016',
               'Happiness_Score_2017',
               'Happiness_Score_2018',
               'Happiness_Score_2019']]

# Renaming the Yearwise Column names
df = df.rename(columns={'Happiness_Score_2015': '2015',
               'Happiness_Score_2016': '2016',
               'Happiness_Score_2017': '2017',
               'Happiness_Score_2018': '2018',
               'Happiness_Score_2019': '2019'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  166 non-null    object
 1   Region   166 non-null    object
 2   2015     160 non-null    float64
 3   2016     159 non-null    float64
 4   2017     157 non-null    float64
 5   2018     158 non-null    float64
 6   2019     158 non-null    float64
dtypes: float64(5), object(2)
memory usage: 9.2+ KB

In [40]:
# Selecting the needed Columns and dropping the unnecessary from the suicide data frame
df_suicide = df_suicide.loc[:,['location','year','val']]

# Renaming the coulumns to match with Happiness data frame
df_suicide = df_suicide.rename(columns={"location": "Country", "year": "Year", "val": "Suicide_Rate"})

# Changing the type of values in Year column to string to match with column names in happiness data frame
df_suicide.Year = df_suicide.Year.astype('str')
df_suicide.head()

                       Country  Year  Suicide_Rate
0                       Malawi  2015      6.675765
1        Sao Tome and Principe  2015      1.947396
2   Western Sub-Saharan Africa  2015      5.255762
3  Latin America and Caribbean  2015      6.433427
4                   Uzbekistan  2015     11.810070

In [41]:
# Checking for Country name mismatches in both data frame
# Listing Country nemes in Happiness but not found in Suicide data frame
mismatch = df[~df.Country.isin(df_suicide.Country)].Country
mismatch

14               United States
22                   Venezuela
30              Czech Republic
47                     Bolivia
48                     Moldova
60                      Russia
64                      Kosovo
69                     Vietnam
91                        Laos
93                   Swaziland
101                       Iran
135                   Tanzania
140                Ivory Coast
145                      Syria
154                     Taiwan
155                  Hong Kong
157                South Korea
158    Palestinian Territories
159           Congo (Kinshasa)
160           Congo (Kinshasa)
161        Congo (Brazzaville)
162        Congo (Brazzaville)
163          Somaliland Region
164            Northern Cyprus
Name: Country, dtype: object

In [42]:
# Checking for Country names in Suicide dataframe which contains, Country names in Happiness dataframe as part of it

temp_df = pd.DataFrame()
for country in mismatch: 
    temp_df2 = df_suicide.loc[df_suicide['Country'].str.contains(country)]
    temp_df = pd.concat([temp_df, temp_df2])
    
temp_df

C:\Users\bimal\anaconda3\lib\site-packages\pandas\core\strings.py:2001: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

                                 Country  Year  Suicide_Rate
111         United States Virgin Islands  2015      8.323183
564             United States of America  2015     14.411347
656             United States of America  2017     14.401417
872         United States Virgin Islands  2017      8.367747
1565            United States of America  2016     14.736476
1641        United States Virgin Islands  2016      8.291533
1979            United States of America  2019     13.826758
2076        United States Virgin Islands  2019      8.452237
2089            United States of America  2018     14.100089
2270        United States Virgin Islands  2018      8.418641
51    Venezuela (Bolivarian Republic of)  2016      8.044487
92    Venezuela (Bolivarian Republic of)  2015      8.157423
1441  Venezuela (Bolivarian Republic of)  2018      8.256628
2230  Venezuela (Bolivarian Republic of)  2017      8.116469
2590  Venezuela (Bolivarian Republic of)  2019      8.229154
179     Bolivia (Plurinational State of)  2015      6.342802
645     Bolivia (Plurinational State of)  2017      6.353022
1987    Bolivia (Plurinational State of)  2019      6.183600
2092    Bolivia (Plurinational State of)  2018      6.287314
2784    Bolivia (Plurinational State of)  2016      6.384799
251                  Republic of Moldova  2015     18.224867
314                  Republic of Moldova  2016     17.328803
1339                 Republic of Moldova  2017     15.682432
1471                 Republic of Moldova  2018     15.145424
3071                 Republic of Moldova  2019     14.895320
158                   Russian Federation  2016     29.080077
1158                  Russian Federation  2015     30.574385
1381                  Russian Federation  2018     27.119921
2215                  Russian Federation  2017     27.175738
2553                  Russian Federation  2019     26.609137
309           Iran (Islamic Republic of)  2015      5.772628
471           Iran (Islamic Republic of)  2016      5.687732
740           Iran (Islamic Republic of)  2017      5.582486
2023          Iran (Islamic Republic of)  2019      4.948817
2921          Iran (Islamic Republic of)  2018      5.356908
39           United Republic of Tanzania  2015      5.550477
352          United Republic of Tanzania  2016      5.553073
1570         United Republic of Tanzania  2018      5.653494
2260         United Republic of Tanzania  2017      5.597909
2622         United Republic of Tanzania  2019      5.695260
15                  Syrian Arab Republic  2015      2.050380
188                 Syrian Arab Republic  2016      2.083871
1443                Syrian Arab Republic  2018      2.144984
2598                Syrian Arab Republic  2019      2.205838
2922                Syrian Arab Republic  2017      2.108724
117           Taiwan (Province of China)  2015     17.357876
779           Taiwan (Province of China)  2017     17.929074
1539          Taiwan (Province of China)  2016     17.783136
1892          Taiwan (Province of China)  2019     18.199449
2763          Taiwan (Province of China)  2018     18.131060

In [43]:
# Changing the Country names in Suicide data frame to match with Happiness dataframe
df_suicide["Country"].loc[df_suicide.Country == "United States of America"] = "United States"
df_suicide["Country"].loc[df_suicide.Country == "Venezuela (Bolivarian Republic of)"] = "Venezuela"
df_suicide["Country"].loc[df_suicide.Country == "Bolivia (Plurinational State of)"] = "Bolivia"
df_suicide["Country"].loc[df_suicide.Country == "Republic of Moldova"] = "Moldova"
df_suicide["Country"].loc[df_suicide.Country == "Russian Federation"] = "Russia"
df_suicide["Country"].loc[df_suicide.Country == "Iran (Islamic Republic of)"] = "Iran"
df_suicide["Country"].loc[df_suicide.Country == "United Republic of Tanzania"] = "Tanzania"
df_suicide["Country"].loc[df_suicide.Country == "Syrian Arab Republic"] = "Syria"
df_suicide["Country"].loc[df_suicide.Country == "Taiwan (Province of China)"] = "Taiwan"

# Again checking for mismatch, Listing Country nemes in Happiness but not found in Suicide data frame
mismatch = df[~df.Country.isin(df_suicide.Country)].Country
mismatch

C:\Users\bimal\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

30              Czech Republic
64                      Kosovo
69                     Vietnam
91                        Laos
93                   Swaziland
140                Ivory Coast
155                  Hong Kong
157                South Korea
158    Palestinian Territories
159           Congo (Kinshasa)
160           Congo (Kinshasa)
161        Congo (Brazzaville)
162        Congo (Brazzaville)
163          Somaliland Region
164            Northern Cyprus
Name: Country, dtype: object

In [44]:
# Checking for Country names in Suicide dataframe which starts with first 4 characters of, 
# Country names in Happiness dataframe as part of it

temp_df = pd.DataFrame()
for country in mismatch: 
    temp_df2 = df_suicide.loc[df_suicide['Country'].str.startswith(country[:4])]
    temp_df = pd.concat([temp_df, temp_df2])
    
temp_df

                                     Country  Year  Suicide_Rate
323                                  Czechia  2015     14.840185
802                                  Czechia  2017     14.358788
1547                                 Czechia  2016     14.476422
1924                                 Czechia  2019     13.900502
3033                                 Czechia  2018     14.220664
79                                  Viet Nam  2015      8.270146
577                                 Viet Nam  2016      8.346326
1353                                Viet Nam  2018      8.429650
2338                                Viet Nam  2017      8.409816
2556                                Viet Nam  2019      8.419432
27                            Southeast Asia  2016      5.487727
54                    Southern Latin America  2015     11.548948
61                                South Asia  2015     12.057804
72                                South Asia  2015     12.057804
98                              South Africa  2015     13.955151
100   Southeast Asia, East Asia, and Oceania  2016      7.775150
194                           South Carolina  2015     15.848215
215                              South Sudan  2015      4.314247
227                         South Kalimantan  2016      3.270499
255                           South Sulawesi  2015      3.114187
311                          South Asia - WB  2015     11.999152
392                   Southern Latin America  2016     11.652750
407              Southern Sub-Saharan Africa  2015     15.054617
422                       South West England  2015      8.527614
425                               South Asia  2016     11.921819
444                       South East England  2016      7.783646
468                       Southeast Sulawesi  2016      3.039119
475                             South Dakota  2016     18.956743
484                               South Asia  2016     11.921819
558                             South Africa  2016     13.336828
594                            South Sumatra  2015      2.709927
666                             South Dakota  2015     18.617085
713                           South Tyneside  2015      8.454799
792                   South-East Asia Region  2016     10.976338
877                              South Sudan  2017      4.452054
880                           South Carolina  2017     15.495300
882              Southern Sub-Saharan Africa  2017     14.670779
905                           South Sulawesi  2017      3.103033
911                       South West England  2017      8.594592
925                               South Asia  2017     11.929566
927                          South Asia - WB  2017     11.873344
931                                Southwark  2016      7.141709
933                          Southend-on-Sea  2016     10.009764
971              Southern Sub-Saharan Africa  2016     14.618560
987                            South Sumatra  2017      2.734199
992                              Southampton  2016     10.040941
1039                          Southeast Asia  2015      5.422378
1086                   South Gloucestershire  2016      5.882161
1097  Southeast Asia, East Asia, and Oceania  2015      7.759489
1120                          South Tyneside  2016      8.502250
1254                      South East England  2015      7.595025
1275                               Southwark  2015      7.414471
1293                   South Gloucestershire  2015      5.813487
1298  Southeast Asia, East Asia, and Oceania  2018      7.749198
1311                          Southeast Asia  2017      5.508860
1336                  Southern Latin America  2018     11.597218
1355                          Southeast Asia  2018      5.516367
1368                  Southern Latin America  2017     11.635746
1404                      Southeast Sulawesi  2015      3.048921
1434                            South Africa  2018     13.911278
1486                         Southend-on-Sea  2015      9.726676
1536                              South Asia  2018     12.327181
1585                        South Kalimantan  2018      3.262082
1622                            South Dakota  2018     18.223900
1674                      Southeast Sulawesi  2018      3.059792
1719                        South Kalimantan  2017      3.289064
1721                      South East England  2018      7.645928
1727                            South Dakota  2017     18.701127
1789                          South Tyneside  2018      8.622034
1799                  South-East Asia Region  2018     11.361834
1804                         Southend-on-Sea  2018      9.986472
1816                             South Sudan  2016      4.427528
1830                             Southampton  2018     10.201388
1839                  South-East Asia Region  2015     11.080083
1841                   South Gloucestershire  2018      5.859991
1886                               Southwark  2018      7.166700
1905                          South Sulawesi  2016      3.105105
2022                              South Asia  2019     12.406289
2051             Southern Sub-Saharan Africa  2019     15.137066
2074                         South Asia - WB  2019     12.327838
2080                             South Sudan  2019      4.512557
2133                           South Sumatra  2016      2.713237
2154                          South Carolina  2019     14.799974
2160                             Southampton  2015      9.418884
2186                           South Sumatra  2019      2.740952
2205                      South West England  2019      8.406716
2239                          South Sulawesi  2019      3.146405
2271                             South Sudan  2018      4.471348
2328                      South West England  2016      8.658582
2470                      South East England  2017      7.697946
2522  Southeast Asia, East Asia, and Oceania  2017      7.764971
2543                          South Carolina  2018     15.129470
2550  Southeast Asia, East Asia, and Oceania  2019      7.702735
2586                              South Asia  2019     12.406289
2601                            South Africa  2019     14.147434
2619                            South Africa  2017     13.424303
2649                      South East England  2019      7.548001
2666                      Southeast Sulawesi  2019      3.057995
2704                  South-East Asia Region  2019     11.435117
2705                          South Tyneside  2019      8.560241
2733                   South Gloucestershire  2019      5.850667
2737                               Southwark  2019      7.319875
2750                         South Asia - WB  2016     11.868055
2799                         Southend-on-Sea  2017      9.998633
2816                  South-East Asia Region  2017     10.993487
2823                           South Sumatra  2018      2.732901
2836                      Southeast Sulawesi  2017      3.067664
2905                          South Tyneside  2017      8.670677
2925                          South Carolina  2016     15.998862
2928                         South Asia - WB  2018     12.258052
2948                   South Gloucestershire  2017      5.922965
3000                             Southampton  2017     10.173617
3002             Southern Sub-Saharan Africa  2018     15.002319
3018                               Southwark  2017      7.103860
3025                              South Asia  2017     11.929566
3055                          Southeast Asia  2019      5.506200
3077                  Southern Latin America  2019     11.537415
3150                        South Kalimantan  2019      3.269221
3157                            South Dakota  2019     17.876688
3217                         Southend-on-Sea  2019      9.905272
3224                             Southampton  2019     10.095179
3246                          South Sulawesi  2018      3.127984
3266                      South West England  2018      8.497439
3275                        South Kalimantan  2015      3.280966
3345                              South Asia  2018     12.327181
384                                Palestine  2016      2.349115
549                                Palestine  2015      2.336830
904                                Palestine  2017      2.339919
2033                               Palestine  2019      2.510734
2993                               Palestine  2018      2.390616
273                                    Congo  2015      7.820624
950                                    Congo  2017      7.803717
1608                                   Congo  2016      7.778691
2043                                   Congo  2019      8.031614
2485                                   Congo  2018      7.906022
273                                    Congo  2015      7.820624
950                                    Congo  2017      7.803717
1608                                   Congo  2016      7.778691
2043                                   Congo  2019      8.031614
2485                                   Congo  2018      7.906022
273                                    Congo  2015      7.820624
950                                    Congo  2017      7.803717
1608                                   Congo  2016      7.778691
2043                                   Congo  2019      8.031614
2485                                   Congo  2018      7.906022
273                                    Congo  2015      7.820624
950                                    Congo  2017      7.803717
1608                                   Congo  2016      7.778691
2043                                   Congo  2019      8.031614
2485                                   Congo  2018      7.906022
240                                  Somalia  2015      6.584438
871                                  Somalia  2017      6.529299
968                                  Somalia  2016      6.556871
2044                                 Somalia  2019      6.511790
2919                                 Somalia  2018      6.540233
21              North Africa and Middle East  2015      4.356508
34                  Northern Mariana Islands  2015     17.901071
75                           North Macedonia  2015      9.737106
162             North Africa and Middle East  2016      4.326284
174                           North Sulawesi  2015      3.634744
196                         Northamptonshire  2015      7.743724
206                            North Sumatra  2015      3.279325
248                         North Kalimantan  2015      1.785414
266                       North West England  2016      9.060016
386                         Northern Ireland  2015     11.432130
465                             North Maluku  2015      3.693391
494                          North Macedonia  2016      9.846217
518                       North East England  2015      9.459245
546                           North Carolina  2015     13.950377
561                             North Dakota  2016     18.839125
586                            North America  2016     14.627444
598                          North Yorkshire  2015      8.391147
633                         Northern Ireland  2016     10.879869
660             North Africa and Middle East  2017      4.306819
665                       North Lincolnshire  2015      8.095135
774                            North Sumatra  2016      3.282929
854                       North East England  2017      9.687590
856                           North Carolina  2017     14.054954
859                 Northern Mariana Islands  2017     18.652693
867                         North Kalimantan  2017      1.795769
878                         Northern Ireland  2017     10.510846
889                           Northumberland  2016      9.107635
995                           North Tyneside  2016      9.759146
1002                      North East England  2016      9.516758
1008                          North Sulawesi  2017      3.734416
1014                 North East Lincolnshire  2015      9.347809
1051            North Africa and Middle East  2015      4.356508
1060                 North East Lincolnshire  2016      9.153228
1107                            North Dakota  2015     18.829884
1110                         North Yorkshire  2017      8.369408
1134                          North Somerset  2016      8.351912
1231                        Northamptonshire  2017      8.036746
1248                            North Maluku  2017      3.660739
1257                      North Lincolnshire  2017      7.897475
1296                          North Somerset  2015      8.242470
1304                           North America  2015     14.336076
1351                          Northumberland  2015      9.288959
1357                          North Tyneside  2015      9.635029
1361                         North Macedonia  2018      9.791582
1416                        Northamptonshire  2016      7.961184
1419            North Africa and Middle East  2017      4.306819
1437                      North West England  2015      9.021343
1509                      North Lincolnshire  2016      7.893313
1524            North Africa and Middle East  2018      4.287984
1611                            North Dakota  2018     17.785255
1633                Northern Mariana Islands  2016     18.577978
1649                           North Sumatra  2018      3.290302
1658                      North West England  2018      9.019428
1712                            North Dakota  2017     18.262568
1748            North Africa and Middle East  2016      4.326284
1785                           North America  2018     14.002489
1831                          Northumberland  2018      9.141971
1865                          North Tyneside  2018     10.052733
1873                          North Somerset  2018      8.216747
1878                          North Sulawesi  2016      3.666615
1880                            North Maluku  2016      3.661286
1885                 North East Lincolnshire  2018      9.230603
2011            North Africa and Middle East  2019      4.238867
2084                Northern Mariana Islands  2019     18.542397
2097            North Africa and Middle East  2018      4.287984
2107                        Northern Ireland  2019     10.403419
2148                          North Carolina  2019     13.579271
2179                      North East England  2019      9.614589
2192                          North Sulawesi  2019      3.819918
2193                        North Kalimantan  2019      1.798971
2212                         North Macedonia  2017      9.845326
2222                            North Maluku  2019      3.679185
2237                        North Kalimantan  2016      1.782068
2353                           North Sumatra  2017      3.300542
2400                      North Lincolnshire  2019      7.844993
2412                         North Yorkshire  2019      8.365837
2413                        Northamptonshire  2019      7.834008
2461                      North West England  2017      9.067447
2486                Northern Mariana Islands  2018     18.658411
2541                          North Carolina  2018     13.812603
2555                         North Macedonia  2019      9.806703
2637                      North West England  2019      9.014157
2648                           North Sumatra  2019      3.289246
2702                 North East Lincolnshire  2019      9.267479
2738                          North Somerset  2019      8.130946
2769                 North East Lincolnshire  2017      9.169768
2777                           North America  2017     14.302969
2778                          Northumberland  2017      9.167680
2779                          North Tyneside  2017     10.018191
2829                          North Sulawesi  2018      3.770711
2837                            North Maluku  2018      3.674223
2865                         North Yorkshire  2018      8.322944
2900                         North Yorkshire  2016      8.301116
2967                        Northern Ireland  2018     10.580673
2996                      North East England  2018      9.670973
3036                      North Lincolnshire  2018      7.828165
3037                          North Somerset  2017      8.309769
3042                        Northamptonshire  2018      7.968754
3117            North Africa and Middle East  2019      4.238867
3142                            North Dakota  2019     17.350491
3190                           North America  2019     13.728844
3194                          Northumberland  2019      9.090228
3198                          North Tyneside  2019      9.984699
3295                        North Kalimantan  2018      1.793350
3339                          North Carolina  2016     14.262313

In [45]:
# Changing the Country names in Suicide data frame to match with Happiness dataframe
df_suicide["Country"].loc[df_suicide.Country == "Czechia"] = "Czech Republic"
df_suicide["Country"].loc[df_suicide.Country == "Viet Nam"] = "Vietnam"
df_suicide["Country"].loc[df_suicide.Country == "Republic of Korea"] = "South Korea"
df_suicide["Country"].loc[df_suicide.Country == "Palestine"] = "Palestinian Territories"
df_suicide["Country"].loc[df_suicide.Country == "Democratic Republic of the Congo"] = "Congo (Kinshasa)"
df_suicide["Country"].loc[df_suicide.Country == "Congo"] = "Congo (Brazzaville)"
df_suicide["Country"].loc[df_suicide.Country == "Lao People's Democratic Republic"] = "Laos"
df_suicide["Country"].loc[df_suicide.Country == "Eswatini"] = "Swaziland"
df_suicide["Country"].loc[df_suicide.Country == "CÃ´te d'Ivoire"] = "Ivory Coast"

# Again checking for mismatch, Listing Country nemes in Happiness but not found in Suicide data frame
mismatch = df[~df.Country.isin(df_suicide.Country)].Country
# The mismatch is due to missing data.
mismatch

C:\Users\bimal\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

64                Kosovo
155            Hong Kong
163    Somaliland Region
164      Northern Cyprus
Name: Country, dtype: object

In [46]:
# Melting the happiness dataframe to make a new column 'Year' 
# Listing the values of Year column
value_vars = ['2015', '2016', '2017', '2018', '2019']

# Melting keeping Country and Region same and Creating Year column, assigning year values and corresponding happiness score
df = pd.melt(df, id_vars=['Country','Region'], value_vars=value_vars,
             var_name='Year', value_name='Happiness_Score', col_level=None)

df.head()

       Country    Region  Year  Happiness_Score
0  Switzerland    Europe  2015            7.587
1      Iceland    Europe  2015            7.561
2      Denmark    Europe  2015            7.527
3       Norway    Europe  2015            7.522
4       Canada  Americas  2015            7.427

In [47]:
# Merging Suicide rates to the happiness dataframe
df = df.merge(df_suicide, left_on=["Country","Year"], right_on=["Country","Year"], how="left")

# Dropping rows with happiness score as NAN
df = df[df['Happiness_Score'].notna()]

# Writing the data to a file to easy access in analysis
df.to_csv("../Output/suicide_concat.csv", index = False)

df.head()

       Country    Region  Year  Happiness_Score  Suicide_Rate
0  Switzerland    Europe  2015            7.587     13.844501
1      Iceland    Europe  2015            7.561     11.103990
2      Denmark    Europe  2015            7.527     11.467831
3       Norway    Europe  2015            7.522     10.965794
4       Canada  Americas  2015            7.427     13.671676